const rand = () => Math.round(Math.random() * 85);
const anomalyRand = () => Math.round(Math.random() * 355 - 5);

const DATA = {
  datasets: [
    {
      label: 'Cluster One',
      data: [
        { x: -48 + rand(), y: -8 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand() , clusterNumber: 1},
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -25 + rand(), y: -25 + rand(), clusterNumber: 1 },
        { x: -48 + rand(), y: -8 + rand(), clusterNumber: 1 },
      ],
      radius: '4',
      backgroundColor: 'rgba(255, 99, 132, .4)',
    },
    {
      label: 'Cluster Two',
      data: [
        { x: 35 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 35 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 35 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
        { x: 65 + rand(), y: -3 + rand() },
      ],
      backgroundColor: 'rgba(119, 101, 227, .7)',
      radius: '4',
    },
    {
      label: 'Cluster Three',
      data: [
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
        { x: 170 + rand(), y: -17 + rand() },
      ],
      backgroundColor: 'rgba(0, 50, 250, .4)',
      radius: '4',
    },
    {
      label: 'Cluster Four',
      data: [
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
        { x: -75 + rand(), y: -80 + -rand() },
      ],
      backgroundColor: 'rgba(150, 250, 250, .4)',
      radius: '4',
    },
    {
      label: 'Cluster Five',
      data: [
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
        { x: 75 + rand(), y: -180 + -rand() },
      ],
      backgroundColor: 'rgba(253, 82, 0, .5)',
      radius: '4',
    },
    {
      label: 'Anomalies',
      data: [
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
        { x: anomalyRand(), y: -anomalyRand() },
      ],
      backgroundColor: 'rgba(0, 0, 0, .3)',
      radius: '4',
    },
    {
      label: 'Cluster Six',
      data: [
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
        { x: 215 + rand(), y: 200 + -rand() },
      ],
      backgroundColor: 'rgba(209, 112, 34, .5)',
      radius: '4',
    },
    {
      label: 'Cluster Seven',
      data: [
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -201 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
        { x: -200 + rand(), y: 150 + -rand() },
      ],
      backgroundColor: 'rgba(42, 252, 152, .5)',
      radius: '4',
    },
  ],
};
  

export default DATA;