export const AUTH_USER = 'AUTH_USER';

export const ADD_DATASET = 'ADD_DATASET';

export const SELECT_DATASET = 'SELECT_DATASET';

export const ASSIGN_MODEL_TO_DEB = 'ASSIGN_MODEL_TO_DEB';

export const CLEAR_DATASETS = 'CLEAR_DATASETS';

export const AUTH_TOKEN = 'AUTH_TOKEN';

export const DATASET_ID = 'DATASET_ID';

export const USER_ID = 'USER_ID';

export const SET_ACTIVE_DATASET_DATA = 'SET_ACTIVE_DATASET_DATA';

export const SET_ORIGINAL_CHART_DATA = 'SET_ORIGINAL_CHART_DATA';

export const SET_ACTIVE_MODEL = 'SET_ACTIVE_MODEL';

export const SET_ALL_MODEL_NAMES = 'SET_ALL_MODEL_NAMES';

export const NEW_MODEL_IS_BEING_CREATED = 'NEW_MODEL_IS_BEING_CREATED';

export const STRIPE_CUSTOMER_ID = 'STRIPE_CUSTOMER_ID';

export const USER_INFO_FOR_AUTO_LOGIN = 'USER_INFO_FOR_AUTO_LOGIN';

export const TOTAL_DATA_USAGE = 'TOTAL_DATA_USAGE';

export const TRACK_ORIGINAL_DATASET_SIZE = 'TRACK_ORIGINAL_DATASET_SIZE';

export const SET_ALL_CLUSTER_NAMES = 'SET_ALL_CLUSTER_NAMES';

export const SET_ACTIVE_MODEL_CLUSTER_EXPLORATION = 'SET_ACTIVE_MODEL_CLUSTER_EXPLORATION';
